apiVersion: webapp.simpletest.com/v1alpha1
kind: Webapp
metadata:
  name: webapp-sample
  labels:
    app: guestbook-ui
spec:
  azureTenantId: "XXX"
  azureSpnId: "XXXX"
  azureSpnSecret: "XXXX"
  storageName: "myTargetStorage"
  versionToDeploy: "v1.2.3.master"
  packageStorageName: "myPackageStorage"

